# OPIc IM3 돌려쓰기 문장 100개. 여기만 고치고 make_opic.py 를 다시 돌린다.
TOPICS = [
 ("만능 문장 (시작·이유·경험·마무리)", [
  ("That's a good question. Let me think about it for a second.", "좋은 질문이네요. 잠깐만 생각해 볼게요."),
  ("Well, to be honest, I've never really thought about it before.", "음, 솔직히 전에는 그것에 대해 별로 생각해 본 적이 없어요."),
  ("Let me tell you about it.", "그것에 대해 말씀드릴게요."),
  ("There are a couple of reasons why I like it.", "제가 그걸 좋아하는 이유가 몇 가지 있어요."),
  ("First of all, it helps me relieve stress.", "우선, 스트레스를 푸는 데 도움이 돼요."),
  ("Plus, it doesn't cost much money.", "게다가 돈도 많이 들지 않아요."),
  ("What I mean is, it makes me feel relaxed.", "제 말은, 그게 저를 편안하게 해 준다는 거예요."),
  ("I usually do this once or twice a week.", "저는 보통 일주일에 한두 번 이걸 해요."),
  ("It's kind of my routine.", "그건 일종의 제 일상이에요."),
  ("I still remember it like it was yesterday.", "마치 어제 일처럼 아직도 기억나요."),
  ("It was one of the best days of my life.", "그날은 제 인생 최고의 날 중 하나였어요."),
  ("I was so surprised that I didn't know what to say.", "너무 놀라서 뭐라고 해야 할지 몰랐어요."),
  ("Looking back, it was a really good experience.", "돌이켜보면, 정말 좋은 경험이었어요."),
  ("Compared to the past, things have changed a lot.", "예전에 비하면 많은 것이 변했어요."),
  ("Anyway, that's pretty much it.", "아무튼, 대충 그 정도예요."),
  ("Thank you for listening.", "들어 주셔서 감사합니다."),
 ]),
 ("자기소개 (1번 문제, 채점 안 됨)", [
  ("Hi, let me introduce myself.", "안녕하세요, 제 소개를 할게요."),
  ("I'm a cheerful and easygoing person.", "저는 밝고 느긋한 성격이에요."),
  ("In my free time, I like to watch movies and take walks in the park.", "여가 시간에는 영화 보는 것과 공원 산책을 좋아해요."),
  ("These days, I'm trying to live a healthier life.", "요즘 저는 더 건강하게 살려고 노력하고 있어요."),
 ]),
 ("집 (거주: 혼자 사는 원룸)", [
  ("I live alone in a studio.", "저는 혼자 원룸(Studio)에 살아요."),
  ("My studio is not that big, but it's cozy.", "제 원룸은 그렇게 크지 않지만, 아늑해요."),
  ("It has a living room that doubles as my bedroom, and a bathroom.", "거실 겸 침실과 화장실이 있어요."),
  ("My favorite place in my home is the living room, which is also my bedroom.", "집에서 제가 제일 좋아하는 곳은 거실 겸 침실이에요."),
  ("In my bedroom, there's a single bed and a computer desk.", "침실에는 싱글침대와 컴퓨터 책상이 있어요."),
  ("When I get home, I usually change my clothes and wash up first.", "집에 오면 보통 먼저 옷을 갈아입고 씻어요."),
  ("On weekends, I clean my house and do the laundry.", "주말에는 집 청소를 하고 빨래를 해요."),
  ("When I moved in, I installed a water purifier just to survive.", "이사 왔을 때 생존을 위해 정수기를 설치했어요."),
  ("Compared to my old place, it's much brighter and quieter.", "예전 집에 비해 훨씬 밝고 조용해요."),
  ("Spending time at home is the best way for me to recharge.", "집에서 시간을 보내는 게 제가 재충전하는 가장 좋은 방법이에요."),
 ]),
 ("공원·산책·조깅", [
  ("There is a big park near my apartment.", "우리 아파트 근처에 큰 공원이 있어요."),
  ("It only takes about five minutes on foot.", "걸어서 5분밖에 안 걸려요."),
  ("There are lots of trees, benches, and a walking trail.", "나무, 벤치, 산책로가 많이 있어요."),
  ("There is also a small lake in the middle of the park.", "공원 한가운데에 작은 호수도 있어요."),
  ("I usually go for a walk there after dinner.", "저는 보통 저녁을 먹고 거기에 산책하러 가요."),
  ("I walk for about an hour while listening to music.", "음악을 들으면서 한 시간 정도 걸어요."),
  ("When I have more energy, I go jogging instead.", "기운이 더 있을 때는 대신 조깅을 해요."),
  ("Walking clears my mind and keeps me healthy.", "걷기는 머리를 맑게 하고 건강을 지켜 줘요."),
  ("Many people walk their dogs or ride bikes there.", "많은 사람들이 거기서 개를 산책시키거나 자전거를 타요."),
  ("One day, it suddenly started to rain while I was walking.", "어느 날 걷고 있는데 갑자기 비가 오기 시작했어요."),
  ("I didn't have an umbrella, so I got completely wet.", "우산이 없어서 완전히 젖었어요."),
 ]),
 ("자전거", [
  ("I enjoy riding my bike along the river.", "저는 강을 따라 자전거 타는 것을 좋아해요."),
  ("There is a nice bike path near my home.", "집 근처에 좋은 자전거 도로가 있어요."),
  ("I usually ride for about an hour on weekends.", "주말에 보통 한 시간 정도 타요."),
  ("Before I ride, I always check the tires and wear a helmet.", "타기 전에 항상 타이어를 확인하고 헬멧을 써요."),
  ("I love feeling the wind on my face.", "얼굴에 바람이 느껴지는 게 정말 좋아요."),
  ("Sometimes I stop at a convenience store and drink something cold.", "가끔 편의점에 들러서 시원한 걸 마셔요."),
  ("Once, I got a flat tire, so I had to walk my bike home.", "한번은 타이어에 펑크가 나서 자전거를 끌고 집까지 걸어가야 했어요."),
  ("These days, many people rent public bikes with an app.", "요즘 많은 사람들이 앱으로 공공자전거를 빌려요."),
 ]),
 ("해변 가기", [
  ("I love going to the beach, especially in summer.", "저는 해변에 가는 것을 좋아해요. 특히 여름에요."),
  ("My favorite beach is Haeundae Beach in Busan.", "제가 제일 좋아하는 해변은 부산 해운대예요."),
  ("The sand is soft, and the water is really clear.", "모래는 부드럽고 물은 정말 맑아요."),
  ("I usually lie on the sand and read a book.", "저는 보통 모래 위에 누워서 책을 읽어요."),
  ("I also like walking along the beach at sunset.", "해 질 녘에 해변을 따라 걷는 것도 좋아해요."),
  ("After swimming, I eat fresh seafood at a restaurant nearby.", "수영한 뒤에는 근처 식당에서 신선한 해산물을 먹어요."),
  ("The last time I went, I forgot to put on sunscreen and got a bad sunburn.", "지난번에 갔을 때 선크림 바르는 걸 깜빡해서 심하게 탔어요."),
  ("Just listening to the waves makes me feel calm.", "파도 소리를 듣기만 해도 마음이 편안해져요."),
 ]),
 ("영화·공연·콘서트 보기", [
  ("I'm a big fan of movies.", "저는 영화를 정말 좋아해요."),
  ("I usually go to the movies with my friends once a month.", "보통 한 달에 한 번 친구들과 영화를 보러 가요."),
  ("My favorite kind of movie is comedy because it makes me laugh.", "제가 제일 좋아하는 영화 장르는 코미디예요. 웃게 해 주니까요."),
  ("Before the movie, I always buy popcorn and a drink.", "영화 보기 전에 항상 팝콘과 음료를 사요."),
  ("These days, I often watch movies at home on Netflix.", "요즘은 집에서 넷플릭스로 영화를 자주 봐요."),
  ("The theater near my house has big screens and comfortable seats.", "우리 집 근처 영화관은 화면이 크고 좌석이 편해요."),
  ("The most memorable movie I've seen recently is Inside Out 2.", "최근에 본 영화 중 가장 기억에 남는 건 인사이드 아웃 2예요."),
  ("The story was so touching that I almost cried.", "이야기가 너무 감동적이라 거의 울 뻔했어요."),
  ("I also like going to concerts to see live performances.", "라이브 공연을 보러 콘서트에 가는 것도 좋아해요."),
  ("Last year, I went to a concert, and everyone sang along together.", "작년에 콘서트에 갔는데 모두가 다 같이 따라 불렀어요."),
  ("The tickets were expensive, but it was totally worth it.", "표가 비쌌지만 그만한 가치가 충분히 있었어요."),
 ]),
 ("음악 감상", [
  ("I listen to music almost every day.", "저는 거의 매일 음악을 들어요."),
  ("I usually listen to K-pop and ballads.", "보통 케이팝과 발라드를 들어요."),
  ("I listen to music on my phone with wireless earphones.", "휴대폰으로 무선 이어폰을 끼고 음악을 들어요."),
  ("When I feel down, music cheers me up.", "기분이 처질 때 음악이 기운을 북돋아 줘요."),
  ("I first got into music when I was in middle school.", "중학교 때 처음 음악에 빠졌어요."),
  ("Back then, I listened to CDs, but now I use streaming apps.", "그때는 CD로 들었지만 지금은 스트리밍 앱을 써요."),
 ]),
 ("국내 여행·집에서 보내는 휴가", [
  ("I like traveling around Korea.", "저는 국내 여행을 좋아해요."),
  ("My favorite place to visit is Jeju Island.", "제가 제일 좋아하는 여행지는 제주도예요."),
  ("Before a trip, I search for good restaurants online.", "여행 전에 인터넷으로 맛집을 찾아봐요."),
  ("I usually pack light, just one small bag.", "저는 보통 작은 가방 하나로 짐을 가볍게 싸요."),
  ("When I don't travel, I spend my vacation at home.", "여행을 안 갈 때는 휴가를 집에서 보내요."),
  ("I sleep in, order food, and binge-watch dramas.", "늦잠을 자고, 음식을 시켜 먹고, 드라마를 몰아 봐요."),
  ("On my last trip, I missed my flight because of heavy traffic.", "지난 여행 때 차가 너무 막혀서 비행기를 놓쳤어요."),
  ("Luckily, I was able to get on the next flight.", "다행히 다음 비행기를 탈 수 있었어요."),
 ]),
 ("은행 (돌발 주제)", [
  ("There is a bank right next to my apartment.", "우리 아파트 바로 옆에 은행이 있어요."),
  ("Inside, there are some ATMs and a few counters.", "안에는 ATM 몇 대와 창구가 몇 개 있어요."),
  ("When I go to the bank, I take a number and wait for my turn.", "은행에 가면 번호표를 뽑고 제 차례를 기다려요."),
  ("These days, I do most of my banking on my phone.", "요즘은 은행 일을 대부분 휴대폰으로 해요."),
  ("Mobile banking is fast and convenient.", "모바일 뱅킹은 빠르고 편리해요."),
  ("I only go to the bank to open an account or exchange money.", "계좌를 만들거나 환전할 때만 은행에 가요."),
  ("Once, I lost my bank card, so I had to get a new one.", "한번은 은행 카드를 잃어버려서 새로 발급받아야 했어요."),
  ("In the past, people had to wait in long lines at the bank.", "예전에는 사람들이 은행에서 길게 줄을 서야 했어요."),
 ]),
 ("롤플레이 (질문하기·문제 해결)", [
  ("Hi, I'm calling to ask about something.", "안녕하세요, 뭐 좀 여쭤보려고 전화했어요."),
  ("I have a few questions for you.", "몇 가지 여쭤볼 게 있어요."),
  ("What time do you open and close?", "몇 시에 문을 열고 닫나요?"),
  ("How much does it cost?", "가격이 얼마예요?"),
  ("Is there a discount for members?", "회원 할인이 있나요?"),
  ("I'm sorry, but I have a problem.", "죄송하지만 문제가 생겼어요."),
  ("I bought a ticket, but I can't make it because I'm sick.", "표를 샀는데 아파서 갈 수가 없어요."),
  ("Can I change it to another day, or get a refund?", "다른 날로 바꾸거나 환불받을 수 있을까요?"),
  ("If that's not possible, how about this?", "그게 안 되면 이렇게 하는 건 어떨까요?"),
  ("Thank you so much for your help.", "도와주셔서 정말 감사합니다."),
 ]),
 ("동네·이웃 (돌발 단골)", [
  ("My neighborhood is quiet and safe.", "우리 동네는 조용하고 안전해요."),
  ("There are many restaurants and cafés near my place.", "우리 집 근처에는 식당과 카페가 많아요."),
  ("There's a convenience store right in front of my building.", "우리 건물 바로 앞에 편의점이 있어요."),
  ("It only takes five minutes to walk to the station.", "역까지 걸어서 5분밖에 안 걸려요."),
  ("I don't know my neighbors very well, but they seem friendly.", "이웃들을 잘 알지는 못하지만 친절한 것 같아요."),
  ("When I first moved here, there weren't many shops.", "제가 처음 이사 왔을 때는 가게가 별로 없었어요."),
  ("These days, a lot of new buildings are going up.", "요즘 새 건물이 많이 들어서고 있어요."),
 ]),
 ("날씨·계절 (돌발 단골)", [
  ("It's hot and humid almost all year round here.", "여기는 거의 일 년 내내 덥고 습해요."),
  ("In the rainy season, it rains heavily almost every afternoon.", "우기에는 거의 매일 오후에 비가 많이 와요."),
  ("I always carry an umbrella with me.", "저는 항상 우산을 가지고 다녀요."),
  ("Korea has four distinct seasons.", "한국은 사계절이 뚜렷해요."),
  ("My favorite season is autumn because the weather is cool and clear.", "제가 제일 좋아하는 계절은 가을이에요. 날씨가 선선하고 맑거든요."),
  ("These days, the weather is hard to predict.", "요즘은 날씨를 예측하기가 어려워요."),
  ("When it's too hot, I just stay inside with the air conditioner on.", "너무 더우면 그냥 에어컨을 켜고 집 안에 있어요."),
 ]),
 ("재활용 (돌발 단골)", [
  ("In my building, we separate the recycling into plastic, paper, and cans.", "우리 건물에서는 재활용을 플라스틱, 종이, 캔으로 나눠요."),
  ("I take out the recycling once a week.", "저는 일주일에 한 번 재활용 쓰레기를 내놓아요."),
  ("I rinse the bottles before I throw them away.", "병은 버리기 전에 헹궈요."),
  ("In Korea, the recycling rules are very strict.", "한국은 재활용 규칙이 아주 엄격해요."),
  ("I try to use a tumbler instead of paper cups.", "종이컵 대신 텀블러를 쓰려고 노력해요."),
  ("I think recycling is a small thing everyone can do for the planet.", "재활용은 누구나 지구를 위해 할 수 있는 작은 일이라고 생각해요."),
 ]),
]
