# -*- coding: utf-8 -*-
# 9학년 수학 3단원 Decimals, percentages and rounding
# 출처 = 선생님 OneNote CHAPTER 3 + 워크시트(Corbettmaths 204 곱셈·92 나눗셈, Compound Interest Exam Style)
VOCAB = [
# ── organ : 10의 거듭제곱 (3.1) ──
("Decimal","소수","A number with a decimal point, such as 251.121.","소수점이 있는 수. 251.121 같은 것.","organ"),
("Decimal point","소수점","The dot that separates whole numbers from parts of a number.","정수 부분과 소수 부분을 가르는 점.","organ"),
("Place value","자릿값","The value a digit has because of its position.","숫자가 놓인 자리에 따라 갖는 값. 소수점이 움직이면 자릿값이 바뀐다.","organ"),
("Power of ten","10의 거듭제곱","Ten multiplied by itself a number of times, such as 10³.","10을 여러 번 곱한 것. 10³ = 1000","organ"),
("Negative power","음의 거듭제곱","A power below zero, meaning one over that power.","지수가 음수인 것. 10⁻² 를 곱하기 = 100으로 나누기.","organ"),
("Multiply","곱하다","To make a number a given number of times bigger.","곱셈을 하다. × 기호로 쓴다.","organ"),
("Divide","나누다","To share a number into equal parts.","나눗셈을 하다. ÷ 기호로 쓴다.","organ"),
("Shift","옮기다","To move the decimal point left or right.","소수점을 왼쪽이나 오른쪽으로 옮기는 것. 10을 곱하면 오른쪽으로 한 칸.","organ"),
("Order","순서대로 놓다","To arrange numbers from smallest to largest or the other way.","수를 크기 순으로 늘어놓는 것. 시험 지시문으로 나온다.","organ"),
("Ascending order","오름차순","From smallest to largest.","작은 것부터 큰 것 순서.","organ"),
("Descending order","내림차순","From largest to smallest.","큰 것부터 작은 것 순서.","organ"),
("Smallest","가장 작은","The least of a group of numbers.","여럿 중 제일 작은 것.","organ"),
("Largest","가장 큰","The greatest of a group of numbers.","여럿 중 제일 큰 것.","organ"),
("Standard form","표준형","A number written as A × 10ⁿ where A is at least 1 and less than 10.","9 × 10³ 처럼 쓴 꼴. 앞 수는 1 이상 10 미만이다.","organ"),
# ── process : 소수의 곱셈·나눗셈 (3.2) ──
("Decimal place","소수 자리","The position of a digit after the decimal point.","소수점 뒤 자리. 1.2 는 소수 1자리다.","process"),
("Whole number","정수","A number with no fractional part.","소수점 아래가 없는 수.","process"),
("Product","곱","The answer to a multiplication.","곱한 결과.","process"),
("Quotient","몫","The answer to a division.","나눈 결과.","process"),
("Dividend","나뉘는 수","The number being divided.","나눗셈에서 앞에 오는 수. 6 ÷ 0.2 의 6.","process"),
("Divisor","나누는 수","The number you divide by.","나눗셈에서 뒤에 오는 수. 6 ÷ 0.2 의 0.2.","process"),
("Equivalent calculation","같은 값의 계산","A different calculation that gives the same answer.","답이 같아지는 다른 계산. 6 ÷ 0.2 = 60 ÷ 2","process"),
("Work out","계산하다","To find the answer.","답을 구하라는 시험 지시문.","process"),
("Give your answer","답을 쓰시오","An instruction to write the final answer.","답을 적으라는 지시문. 뒤에 자리수 조건이 붙는 경우가 많다.","process"),
("Cost","값·비용","How much something is priced at.","물건 값. £6.70 per hour 처럼 나온다.","process"),
("Total cost","총액","The whole amount of money for everything.","전부 더한 값.","process"),
("Per hour","시간당","For each hour.","한 시간마다. £6.70 per hour × 8시간.","process"),
("Per metre","미터당","For each metre.","1미터마다의 값.","process"),
("How many","몇 개","A question asking for a number of items.","개수를 묻는 말. 나눗셈으로 푼다.","process"),
("Unit","단위","A standard used to measure, such as g, kg or cm.","g·kg·cm 같은 재는 기준.","process"),
("Convert","단위를 바꾸다","To change from one unit to another.","단위를 바꾸는 것. 40 kg = 40,000 g","process"),
("Thickness","두께","How thick something is.","물건이 두꺼운 정도. 교과서 2.5 cm 문제에 나온다.","process"),
# ── blood : 퍼센트·복리 (3.3) ──
("Percentage","백분율","A part out of one hundred.","100을 기준으로 나타낸 비율.","blood"),
("Per cent","퍼센트","Out of one hundred; the symbol is %.","100분의 몇. 기호는 %.","blood"),
("Increase","증가하다","To make or become larger.","커지는 것. 20% increase = ×1.2","blood"),
("Decrease","감소하다","To make or become smaller.","작아지는 것. 20% decrease = ×0.8","blood"),
("Multiplier","배수","The number you multiply by to do a percentage change in one step.","퍼센트 변화를 한 번에 하는 곱하는 수. 8% 증가는 ×1.08.","blood"),
("Compound interest","복리","Interest worked out on the total that already includes earlier interest.","이자에 다시 이자가 붙는 것. 둘째 해에는 불어난 금액에 이자가 붙는다.","blood"),
("Simple interest","단리","Interest worked out on the starting amount only.","처음 원금에만 이자가 붙는 것. 복리와 다르다.","blood"),
("Compound percentage","반복되는 퍼센트","A percentage change applied again and again.","퍼센트 변화가 해마다 되풀이되는 것. 3.3 단원 제목이다.","blood"),
("Interest","이자","The extra money paid for saving or borrowing.","돈을 맡기거나 빌릴 때 붙는 돈.","blood"),
("Invest","투자하다","To put money in so that it grows.","돈을 맡겨 불리는 것.","blood"),
("Principal","원금","The starting amount of money.","처음 넣은 돈. 이자만 물으면 마지막에 이걸 뺀다.","blood"),
("Per annum","연간","Each year; often written p.a.","해마다. 2.8% per annum = 연 2.8%.","blood"),
("Depreciate","값이 떨어지다","To lose value over time.","시간이 지나며 값이 줄어드는 것. 차·TV에 쓴다.","blood"),
("Depreciation","감가","The loss in value over time.","값이 떨어지는 것 자체.","blood"),
("Original value","처음 값","The value before any change.","변하기 전의 값.","blood"),
("Rate","비율","The percentage used each time.","매번 적용하는 퍼센트.","blood"),
("Growth","증가","Getting bigger over time.","시간이 지나며 커지는 것.","blood"),
("Decay","감소","Getting smaller over time.","시간이 지나며 줄어드는 것. 방사성 물질 문제에 나온다.","blood"),
("Bounce","튀어 오르다","To spring back up after hitting the ground.","공이 바닥에 닿고 다시 올라오는 것.","blood"),
("Leak","새다","To lose liquid slowly through a hole.","물이 조금씩 빠져나가는 것.","blood"),
("Radioactive","방사성의","Giving off radiation and losing mass over time.","시간이 지나며 양이 줄어드는 물질에 쓴다.","blood"),
("Double","두 배가 되다","To become twice as large.","두 배로 커지는 것.","blood"),
("At least","적어도","Not less than the given amount.","그 값 이상. £3200 이상이 되는 햇수를 묻는다.","blood"),
("Exceed","넘다","To go above a given amount.","어떤 값을 넘어서는 것.","blood"),
# ── gas : 반올림·상한·하한 (3.4) ──
("Round","반올림하다","To change a number to a nearby simpler value.","가까운 값으로 고치는 것.","gas"),
("Rounded","반올림된","Already changed to a nearby simpler value.","이미 반올림된 상태. 상한·하한 문제의 출발점이다.","gas"),
("Nearest integer","가장 가까운 정수","The closest whole number.","제일 가까운 정수. 24 (nearest integer) → ±0.5","gas"),
("Significant figure","유효숫자","A digit counted from the first non-zero digit.","0이 아닌 첫 숫자부터 센 자릿수. 줄여서 s.f.","gas"),
("Upper bound","상한","The largest value a rounded number could have been.","반올림 전에 될 수 있었던 가장 큰 값.","gas"),
("Lower bound","하한","The smallest value a rounded number could have been.","반올림 전에 될 수 있었던 가장 작은 값.","gas"),
("Half","절반","One of two equal parts.","반. 반올림한 자리의 절반만큼 위아래로 벌린다.","gas"),
("Accurate to","~까지 정확한","Correct up to the stated place.","어느 자리까지 맞다는 뜻. accurate to 1 d.p.","gas"),
("Measurement","측정값","A value found by measuring.","재서 얻은 값. 반올림돼 있으므로 상한·하한이 있다.","gas"),
("Estimate","어림하다","To find an approximate answer.","대략의 답을 구하는 것.","gas"),
("Approximately","대략","Nearly but not exactly.","정확히는 아니고 거의. 기호는 ≈.","gas"),
("Neighbour","이웃 값","The numbers on either side at that rounding level.","그 자릿수에서 양옆에 오는 수. 400의 이웃은 300과 500이다.","gas"),
]
CATS = [("organ","🔟 10의 거듭제곱 Powers of 10"),("process","✖️ 소수 계산 Decimals"),
        ("blood","📈 퍼센트·복리 Percentages"),("gas","📏 반올림·상한하한 Bounds")]
