# -*- coding: utf-8 -*-
# 9학년 수학 4단원 Equations and inequalities
# 출처 = 선생님 OneNote CHAPTER 4 + 워크시트(Corbettmaths 110 방정식·113 양변 글자·295 연립방정식, 부등식 문제)
VOCAB = [
# ── organ : 방정식 풀기 (4.1) ──
("Equation","방정식","Two expressions joined by an equals sign.","등호(=)가 있는 식. 값을 구해 풀 수 있다.","organ"),
("Solve","풀다","To find the value of the unknown letter.","모르는 글자의 값을 찾아내는 것. 가장 많이 나오는 지시문이다.","organ"),
("Solution","해","The value that makes the equation true.","넣었을 때 식이 성립하는 값.","organ"),
("Unknown","미지수","The letter whose value you are looking for.","값을 모르는 글자. 보통 x 로 쓴다.","organ"),
("Both sides","양변","The left and the right of the equals sign.","등호의 왼쪽과 오른쪽. 무엇을 하든 양쪽에 똑같이 한다.","organ"),
("Balance","균형","Keeping both sides equal.","양쪽이 같은 상태를 유지하는 것. 방정식은 저울과 같다.","organ"),
("Inverse operation","역연산","The operation that undoes another one.","반대 연산. 더하기↔빼기, 곱하기↔나누기.","organ"),
("Isolate","혼자 남기다","To get the letter by itself on one side.","글자 하나만 한쪽에 남기는 것.","organ"),
("Coefficient","계수","The number in front of the letter.","글자 앞에 붙은 숫자. 3w 의 계수는 3.","organ"),
("Two-step equation","두 단계 방정식","An equation needing two inverse operations.","두 번 풀어야 하는 식. 2x + 3 = 9 같은 것.","organ"),
("Substitute","대입하다","To put a number in place of a letter.","글자 자리에 수를 넣는 것. 답을 검산할 때 쓴다.","organ"),
("Check","검산하다","To put your answer back in to see if it works.","구한 답을 다시 넣어 맞는지 보는 것.","organ"),
("Construct an equation","방정식을 세우다","To write an equation from a word problem.","문장을 읽고 식을 만드는 것. 4.1 단원 제목이다.","organ"),
("Perimeter","둘레","The total distance around the edge of a shape.","도형 둘레의 길이. 둘레 = (가로 + 세로) × 2","organ"),
("Rectangle","직사각형","A shape with four right angles; opposite sides are equal.","네 각이 직각인 사각형. 마주 보는 변의 길이가 같다.","organ"),
("Isosceles triangle","이등변삼각형","A triangle with two sides of equal length.","두 변의 길이가 같은 삼각형. 그 두 변을 같다고 놓고 식을 세운다.","organ"),
("Opposite sides","마주 보는 변","The sides facing each other in a rectangle.","직사각형에서 서로 마주 본 변. 길이가 같다.","organ"),
("No solution","해가 없다","No value of the letter makes the equation true.","어떤 값을 넣어도 성립하지 않는 것. 8x+3 = 8x+2 처럼 3 = 2 가 되면 해가 없다.","organ"),
# ── process : 양쪽에 글자가 있을 때 (4.1 후반) ──
("Letters on both sides","양변에 글자","The unknown appears on the left and the right.","글자가 등호 양쪽에 다 있는 식.","process"),
("Collect","모으다","To bring like terms together on one side.","같은 것끼리 한쪽으로 모으는 것.","process"),
("Like terms","동류항","Terms with exactly the same letters and powers.","글자와 지수가 같은 항들. 4x 와 2x 는 동류항.","process"),
("Move across","반대쪽으로 넘기다","To take a term to the other side, changing its sign.","항을 반대쪽으로 옮기는 것. 부호가 바뀐다.","process"),
("Expand","전개하다","To multiply out the brackets.","괄호를 풀어 곱하는 것. 5(x+3) = 5x + 15","process"),
("Bracket","괄호","A symbol grouping part of a calculation.","묶음 표시. 방정식에서는 먼저 푼다.","process"),
("Simplify","간단히 하다","To write the expression in its shortest form.","더 짧게 정리하는 것.","process"),
("Negative answer","음수 답","An answer below zero.","답이 0보다 작은 것. 틀린 게 아니다.","process"),
("Fraction answer","분수 답","An answer that is a fraction.","답이 분수로 나오는 것. 7/2 처럼 그대로 써도 된다.","process"),
("Denominator","분모","The number on the bottom of a fraction.","분수 아래쪽 수. 양변에 곱해 없앤다.","process"),
("Multiply both sides","양변에 곱하다","To multiply the left and right by the same number.","양쪽에 같은 수를 곱하는 것. 분수를 없앨 때 쓴다.","process"),
("Explain why","이유를 설명하시오","An instruction asking for a written reason.","까닭을 글로 쓰라는 지시문. 답만 쓰면 점수가 깎인다.","process"),
# ── blood : 연립방정식 (4.2) ──
("Simultaneous equations","연립방정식","Two equations that are true at the same time.","동시에 성립하는 두 식. x 와 y 를 둘 다 구한다.","blood"),
("Elimination","소거법","Removing one unknown by adding or subtracting the equations.","두 식을 더하거나 빼서 글자 하나를 없애는 방법.","blood"),
("Eliminate","없애다","To get rid of one of the unknowns.","글자 하나를 지우는 것.","blood"),
("Add the equations","두 식을 더하다","To add the left sides and the right sides together.","두 식을 세로로 더하는 것. 부호가 다를 때 쓴다.","blood"),
("Subtract the equations","두 식을 빼다","To take one equation away from the other.","두 식을 빼는 것. 부호가 같을 때 쓴다.","blood"),
("Same sign","같은 부호","Both terms are positive or both negative.","둘 다 + 이거나 둘 다 − 인 것. 이때는 뺀다.","blood"),
("Different sign","다른 부호","One term is positive and the other negative.","하나는 +, 하나는 − 인 것. 이때는 더한다.","blood"),
("Match the coefficients","계수를 맞추다","To multiply an equation so the numbers in front line up.","한 식에 수를 곱해 앞 숫자를 같게 만드는 것.","blood"),
("Substitute back","다시 대입하다","To put the found value into one equation to get the other.","구한 값을 원래 식에 넣어 나머지를 구하는 것.","blood"),
("Pair of values","값의 짝","The x and y that solve both equations.","두 식을 모두 만족하는 x 와 y 한 쌍.","blood"),
("Simultaneously","동시에","At the same time.","같은 때에. 두 식이 함께 성립한다는 뜻이다.","blood"),
# ── gas : 부등식 (4.3) ──
("Inequality","부등식","A statement using <, >, ≤ or ≥ instead of =.","등호 대신 부등호를 쓴 식. 4.3 단원 제목이다.","gas"),
("Inequality sign","부등호","The symbol <, >, ≤ or ≥.","<, >, ≤, ≥ 기호.","gas"),
("Greater than","보다 크다","The symbol >.","> 기호. x > 3 은 x 가 3보다 크다는 뜻.","gas"),
("Less than","보다 작다","The symbol <.","< 기호. x < 5 는 x 가 5보다 작다는 뜻.","gas"),
("Greater than or equal to","크거나 같다","The symbol ≥.","≥ 기호. 그 값도 포함한다.","gas"),
("Less than or equal to","작거나 같다","The symbol ≤.","≤ 기호. 그 값도 포함한다.","gas"),
("Reverse","뒤집다","To turn the inequality sign the other way.","부등호 방향을 반대로 바꾸는 것.","gas"),
("Divide by a negative","음수로 나누다","To divide both sides by a number below zero.","음수로 나누는 것. 이때 부등호가 뒤집힌다.","gas"),
("Combined inequality","이중 부등식","An inequality with a value on each side, such as 1 < x < 9.","1 < x < 9 처럼 양쪽에 수가 있는 것.","gas"),
("Solution set","해집합","All the values that satisfy the inequality.","조건을 만족하는 값을 다 모은 것. {24, 25} 처럼 쓴다.","gas"),
("Integer","정수","A whole number, positive, negative or zero.","소수·분수가 아닌 수. 해집합을 정수로 고를 때 쓴다.","gas"),
("Satisfy","만족하다","To make the inequality true.","조건에 맞는 것.","gas"),
("Range of values","값의 범위","All the numbers between two limits.","두 값 사이의 모든 수.","gas"),
]
CATS = [("organ","⚖️ 방정식 풀기 Solving"),("process","🔁 양변에 글자 Both sides"),
        ("blood","🔗 연립방정식 Simultaneous"),("gas","≤ 부등식 Inequalities")]
