# -*- coding: utf-8 -*-
# 9학년 수학 5단원 Angles
# 출처 = y9m_ch5_problems.html (선생님 OneNote CHAPTER 5 + PPT 3개 + Pythagoras 워크시트)
VOCAB = [
# ── organ : 각의 종류와 각 사이의 관계 (5.1 앞부분) ──
("Angle","각","The amount of turn between two lines that meet at a point.","한 점에서 만나는 두 선이 벌어진 정도. 단위는 도(°).","organ"),
("Protractor","각도기","A tool for measuring and drawing angles.","각을 재고 그리는 도구. 눈금이 바깥·안쪽 두 줄이다.","organ"),
("Acute angle","예각","An angle more than 0° and less than 90°.","0°보다 크고 90°보다 작은 각.","organ"),
("Right angle","직각","An angle of exactly 90°.","정확히 90°인 각. 모서리에 작은 네모로 표시한다.","organ"),
("Obtuse angle","둔각","An angle more than 90° and less than 180°.","90°보다 크고 180°보다 작은 각.","organ"),
("Straight angle","평각","An angle of exactly 180°.","정확히 180°인 각. 일직선이다.","organ"),
("Reflex angle","우각","An angle more than 180° and less than 360°.","180°보다 크고 360°보다 작은 각. 오목한 꼭짓점의 각이 이것이다.","organ"),
("Full rotation","한 바퀴","A complete turn of 360°.","한 바퀴 돈 각. 360°.","organ"),
("Complementary angles","여각","Two angles that add up to 90°.","합이 90°인 두 각. 직각 안의 각들.","organ"),
("Supplementary angles","보각","Two angles that add up to 180°.","합이 180°인 두 각. 직선 위의 각들.","organ"),
("Angles on a straight line","직선 위의 각","Angles on a straight line add up to 180°.","한 직선 위에 붙은 각들. 합이 180°. 이유 쓰기에 그대로 쓰는 문장이다.","organ"),
("Angles at a point","한 점 주위의 각","Angles around a point add up to 360°.","한 점을 빙 둘러싼 각들. 합이 360°.","organ"),
("Vertically opposite angles","맞꼭지각","Angles opposite each other where two lines cross; they are equal.","두 직선이 엇갈릴 때 마주 보는 두 각. 크기가 같다.","organ"),
("Angle notation","각 기호","Writing an angle with three letters, such as ∠ABC.","각을 세 글자로 쓰는 법. ∠ABC 또는 AB̂C.","organ"),
("Vertex","꼭짓점","The point where the two arms of an angle meet.","각의 두 팔이 만나는 점. ∠ABC 에서는 가운데 글자 B 다.","organ"),
("Arm","팔(변)","One of the two lines that make an angle.","각을 이루는 두 선 중 하나.","organ"),
("Reason","이유","A written rule that explains your answer.","답이 왜 맞는지 쓰는 규칙 문장. 시험에서 따로 점수가 있다.","organ"),
("Not drawn accurately","정확히 그린 그림 아님","The diagram is not to scale, so you must calculate, not measure.","그림이 실제 크기가 아니다. 각도기로 재지 말고 계산하라는 뜻.","organ"),
# ── process : 평행선·삼각형·사각형 (5.1 뒷부분) ──
("Parallel lines","평행선","Lines that never meet and stay the same distance apart.","절대 만나지 않는 두 직선. 그림에서 화살표(>)로 표시한다.","process"),
("Corresponding angles","동위각","Angles in the same position at each parallel line; F-shape; they are equal.","평행선 위 같은 자리에 있는 각. F 모양. 크기가 같다.","process"),
("Alternate angles","엇각","Angles on opposite sides between parallel lines; Z-shape; they are equal.","평행선 사이에서 엇갈린 자리의 각. Z 모양. 크기가 같다.","process"),
("Co-interior angles","동측내각","Angles on the same side between parallel lines; C-shape; they add up to 180°.","평행선 사이 같은 쪽에 있는 각. C 모양. 합이 180°.","process"),
("Perpendicular","수직의","Meeting at a right angle.","직각으로 만나는 것.","process"),
("Quadrilateral","사각형","A shape with four straight sides.","곧은 변이 네 개인 도형. 네 각의 합은 360°.","process"),
("Parallelogram","평행사변형","A quadrilateral with two pairs of parallel sides.","마주 보는 변이 두 쌍 다 평행한 사각형. 마주 보는 각이 같다.","process"),
("Rectangle","직사각형","A quadrilateral with four right angles.","네 각이 모두 직각인 사각형.","process"),
("Square","정사각형","A quadrilateral with four equal sides and four right angles.","네 변이 같고 네 각이 직각인 사각형.","process"),
("Rhombus","마름모","A quadrilateral with four equal sides.","네 변의 길이가 모두 같은 사각형.","process"),
("Trapezium","사다리꼴","A quadrilateral with one pair of parallel sides.","평행한 변이 한 쌍뿐인 사각형.","process"),
("Kite","연꼴","A quadrilateral with two pairs of equal adjacent sides.","이웃한 변끼리 두 쌍이 같은 사각형. 연 모양.","process"),
("Diagonal","대각선","A line joining two corners that are not next to each other.","이웃하지 않은 두 꼭짓점을 잇는 선.","process"),
("Symmetry","대칭","When one half is a mirror image of the other.","반으로 접으면 꼭 맞는 성질.","process"),
("Opposite angles","마주 보는 각","Angles facing each other in a quadrilateral.","사각형에서 서로 마주 보는 각. 평행사변형에서는 같다.","process"),
("Equilateral triangle","정삼각형","A triangle with three equal sides; each angle is 60°.","세 변이 같은 삼각형. 세 각이 모두 60°.","process"),
("Isosceles triangle","이등변삼각형","A triangle with two equal sides and two equal base angles.","두 변이 같은 삼각형. 두 밑각이 같다.","process"),
("Base angles","밑각","The two equal angles at the bottom of an isosceles triangle.","이등변삼각형에서 같은 두 변의 밑에 있는 두 각. 크기가 같다.","process"),
("Angle sum of triangle","삼각형 내각의 합","The three angles in a triangle add up to 180°.","삼각형 세 각의 합. 늘 180°.","process"),
("Opposite interior angles","이웃하지 않은 두 내각","The two inside angles of a triangle not next to the exterior angle.","외각과 붙어 있지 않은 삼각형 안쪽 두 각. 둘을 더하면 외각과 같다.","process"),
# ── blood : 다각형의 내각과 외각 (5.2 · 5.3) ──
("Polygon","다각형","A closed flat shape made of straight sides.","곧은 변으로 둘러싸인 닫힌 평면도형.","blood"),
("Regular polygon","정다각형","A polygon with all sides and all angles equal.","모든 변과 모든 각이 같은 다각형.","blood"),
("Irregular polygon","정다각형이 아닌 다각형","A polygon whose sides or angles are not all equal.","변이나 각이 다 같지는 않은 다각형.","blood"),
("Pentagon","오각형","A polygon with 5 sides.","변이 5개. 내각의 합 540°.","blood"),
("Hexagon","육각형","A polygon with 6 sides.","변이 6개. 내각의 합 720°.","blood"),
("Heptagon","칠각형","A polygon with 7 sides.","변이 7개. 내각의 합 900°.","blood"),
("Octagon","팔각형","A polygon with 8 sides.","변이 8개. 내각의 합 1080°.","blood"),
("Nonagon","구각형","A polygon with 9 sides.","변이 9개. 내각의 합 1260°.","blood"),
("Decagon","십각형","A polygon with 10 sides.","변이 10개. 내각의 합 1440°.","blood"),
("Dodecagon","십이각형","A polygon with 12 sides.","변이 12개. 내각의 합 1800°.","blood"),
("Icosagon","이십각형","A polygon with 20 sides.","변이 20개. 내각의 합 3240°.","blood"),
("Interior angle","내각","An angle inside a polygon at a vertex.","다각형 안쪽의 각.","blood"),
("Sum of interior angles","내각의 합","All the interior angles added together: 180(n − 2).","내각을 다 더한 값. n각형이면 180 × (n − 2).","blood"),
("Exterior angle","외각","The angle between one side extended and the next side.","한 변을 늘인 선과 이웃 변 사이의 각. 내각 + 외각 = 180°.","blood"),
("Sum of the exterior angles","외각의 합","The exterior angles of any polygon add up to 360°.","외각을 다 더한 값. 변이 몇 개든 늘 360°.","blood"),
("Number of sides","변의 수","How many sides the polygon has, written n.","다각형 변의 개수. 보통 n 으로 쓴다.","blood"),
("Consecutive","연속하는","Following one after another without a gap, such as 106, 107, 108.","빠짐없이 하나씩 이어지는 것. 106, 107, 108 처럼.","blood"),
# ── gas : 작도와 피타고라스 정리 (5.4 · 5.5) ──
("Construction","작도","Drawing accurately with only a ruler and compasses.","자와 컴퍼스만으로 정확하게 그리는 것.","gas"),
("Bisect","이등분하다","To cut into two equal parts.","똑같이 둘로 나누는 것. 60°를 이등분하면 30°.","gas"),
("Perpendicular bisector","수직이등분선","A line that cuts a segment in half at a right angle.","선분을 반으로 나누면서 직각으로 지나는 선.","gas"),
("Inscribe","내접시키다","To draw a shape inside a circle with every vertex on the circle.","꼭짓점이 모두 원 위에 오도록 원 안에 그리는 것.","gas"),
("Diameter","지름","A straight line across a circle through its centre.","원의 중심을 지나 양끝이 원 위에 있는 선.","gas"),
("Pythagoras' theorem","피타고라스 정리","In a right-angled triangle, a² + b² = c².","직각삼각형에서 두 짧은 변의 제곱의 합 = 빗변의 제곱.","gas"),
("Hypotenuse","빗변","The longest side, opposite the right angle.","직각의 맞은편에 있는 가장 긴 변.","gas"),
("Right-angled triangle","직각삼각형","A triangle with one angle of 90°.","한 각이 90°인 삼각형.","gas"),
("Decimal places","소수 자리","The digits after the decimal point.","소수점 아래 자리. 2 d.p. 는 소수 둘째 자리까지.","gas"),
("Perimeter","둘레","The total distance around the edge of a shape.","도형 둘레의 길이.","gas"),
("Area","넓이","The amount of space inside a flat shape.","도형 안쪽 크기. 삼각형은 ½ × 밑변 × 높이.","gas"),
]
CATS = [("organ","📐 각과 관계 Angle facts"),("process","∥ 평행선·삼각형·사각형 Parallel lines"),
        ("blood","⬡ 다각형 Polygons"),("gas","📏 작도·피타고라스 Pythagoras")]
