# -*- coding: utf-8 -*-
# 9학년 수학 2단원 Expressions and formulae 단어장
# 출처 = 선생님 클래스룸 자료(OneNote CHAPTER 2 + 워크시트 Corbettmaths 16/14/21, Dr Frost 지수법칙·주어바꾸기)
VOCAB = [
# ── organ : 식의 기본 (2.1 대입 · 2.2 식 세우기) ──
("Expression","식","A group of numbers and letters joined by + − × ÷, with no equals sign.","숫자와 글자를 계산기호로 이은 것. 등호(=)가 없다. 예 3x + 4","organ"),
("Formula","공식","A rule written with letters that links two or more quantities.","글자로 쓴 규칙. 등호가 있다. 예 P = W + RH","organ"),
("Formulae","공식(복수형)","The plural of formula.","formula의 복수형. 시험지에 formulae 라고 나온다.","organ"),
("Term","항","Each separate part of an expression, split by + or −.","+ 나 − 로 나뉘는 한 덩어리. 3x + 4 에서 3x 와 4 가 각각 항이다.","organ"),
("Coefficient","계수","The number in front of a letter in a term.","글자 앞에 붙은 숫자. 5y 의 계수는 5 다.","organ"),
("Variable","변수","A letter that stands for a value that can change.","값이 변할 수 있는 글자. x, y, n 같은 것.","organ"),
("Constant","상수","A number in an expression that never changes.","변하지 않는 숫자. 2x + 7 에서 7 이 상수다.","organ"),
("Substitute","대입하다","To replace a letter with a given number.","글자 자리에 주어진 숫자를 넣는 것. f = 5 면 fg 는 5 × g 가 된다.","organ"),
("Substitution","대입","Replacing letters with numbers to find the value of an expression.","글자에 숫자를 넣어 값을 구하는 것. 2.1 단원 제목이다.","organ"),
("Evaluate","값을 구하다","To work out the value of an expression.","식의 값을 계산해 내는 것.","organ"),
("Find the value of","~의 값을 구하시오","An instruction asking you to substitute and calculate.","시험에 가장 많이 나오는 지시문. 대입해서 계산하라는 뜻이다.","organ"),
("Construct an expression","식을 세우다","To write an expression from a sentence in words.","말로 된 문장을 식으로 옮기는 것. 2.2 단원 제목이다.","organ"),
("Order of operations","계산 순서","The rule that brackets come first, then indices, then × and ÷, then + and −.","괄호 → 지수 → 곱셈·나눗셈 → 덧셈·뺄셈 순서로 계산하는 규칙.","organ"),
("BIDMAS","계산 순서 규칙","Brackets, Indices, Division, Multiplication, Addition, Subtraction.","Brackets(괄호) Indices(지수) Division(나눗셈) Multiplication(곱셈) Addition(덧셈) Subtraction(뺄셈)의 앞글자.","organ"),
("Bracket","괄호","A symbol that groups part of a calculation so it is done first.","묶어서 먼저 계산하라는 표시. 4(n + 3) 처럼 쓴다.","organ"),
("Perimeter","둘레","The total distance all the way around the edge of a shape.","도형의 가장자리를 한 바퀴 돈 길이. 모든 변을 더한다.","organ"),
("Area","넓이","The amount of surface a shape covers.","도형이 덮는 넓이. 직사각형은 가로 × 세로.","organ"),
("Circumference","원의 둘레","The distance around the outside of a circle, C = 2πr.","원을 한 바퀴 돈 길이. C = 2πr","organ"),
("Radius","반지름","The distance from the centre of a circle to its edge.","원의 중심에서 가장자리까지의 거리.","organ"),
("Sector","부채꼴","A slice of a circle between two radii.","원을 피자 조각처럼 자른 부분. 원 전체의 (중심각/360) 만큼이다.","organ"),
("Cone","원뿔","A solid with a circular base rising to a point, V = ⅓πr²h.","밑면이 원이고 위가 뾰족한 입체. 부피 V = ⅓πr²h","organ"),
("Cuboid","직육면체","A box-shaped solid with six rectangular faces.","직사각형 면 6개로 된 상자 모양 입체.","organ"),
("Surface area","겉넓이","The total area of all the faces of a solid.","입체의 모든 면의 넓이를 더한 것. A = 2lh + 2wh + 2lw","organ"),
("Volume","부피","The amount of space a solid takes up.","입체가 차지하는 공간의 크기.","organ"),
("Isosceles triangle","이등변삼각형","A triangle with two sides of equal length.","두 변의 길이가 같은 삼각형. 그림의 빗금(tick)이 같은 변을 뜻한다.","organ"),
("Compound interest","복리","Interest worked out on the total that already includes earlier interest.","이자에 다시 이자가 붙는 것. A = P(1 + R/100)ⁿ","organ"),
# ── process : 지수 (2.3) ──
("Index","지수","The small raised number showing how many times the base is multiplied by itself.","작게 위에 쓴 숫자. x⁵ 에서 5 가 지수다.","process"),
("Indices","지수(복수형)","The plural of index.","index의 복수형. 2.3 단원 제목에 쓰인다.","process"),
("Base","밑","The number or letter that is raised to a power.","거듭제곱의 아래쪽 수. x⁵ 에서 x 가 밑이다.","process"),
("Power","거듭제곱","Another word for index; also the whole expression such as 2 to the power 5.","같은 수를 여러 번 곱한 것. 2⁵ 을 '2의 5제곱'이라 읽는다.","process"),
("Index law","지수 법칙","A rule for adding, subtracting or multiplying indices.","같은 밑일 때만 쓰는 규칙. 곱하면 더하고 나누면 뺀다.","process"),
("Laws of indices","지수 법칙(들)","The full set of index rules used in this unit.","aᵐ × aⁿ = aᵐ⁺ⁿ, aᵐ ÷ aⁿ = aᵐ⁻ⁿ, (aᵐ)ⁿ = aᵐⁿ, a⁰ = 1","process"),
("Negative index","음의 지수","An index below zero, meaning one over that power.","지수가 음수면 분모로 내려간다. 12x⁻¹ = 12/x","process"),
("Fractional index","분수 지수","An index written as a fraction, such as one half.","지수가 분수인 것. m¹ᐟ⁴ × m⁰·² 처럼 더해서 계산한다.","process"),
("Zero index","0제곱","Any number to the power zero equals 1.","무엇이든 0제곱은 1이다. 0이 아니다 — 시험 단골 함정.","process"),
("Simplify","간단히 하다","To write an expression in its shortest form.","더 짧게 정리하는 것. 시험 지시문으로 가장 많이 나온다.","process"),
("Reciprocal","역수","One divided by a number; the fraction turned upside down.","1을 그 수로 나눈 것. 3/4 의 역수는 4/3 이다.","process"),
("Square root","제곱근","The number that gives the original when multiplied by itself.","제곱하면 원래 수가 되는 수. √4 = 2","process"),
("Squared","제곱된","Multiplied by itself, shown by a small 2.","자기 자신과 한 번 곱한 것. e squared = e²","process"),
("Cubed","세제곱된","Multiplied by itself three times, shown by a small 3.","자기 자신을 세 번 곱한 것. i³ = 2³ = 8","process"),
# ── blood : 괄호 전개 (2.4) ──
("Expand","전개하다","To multiply out the brackets.","괄호를 풀어 곱해 주는 것. 2.4 단원 제목이다.","blood"),
("Expand and simplify","전개하고 정리하시오","Multiply out the brackets, then collect like terms.","괄호를 풀고 동류항까지 모아 정리하라는 지시문.","blood"),
("Product","곱","The answer to a multiplication.","곱한 결과. '두 식의 product' = 두 식을 곱하라는 뜻이다.","blood"),
("Linear expression","일차식","An expression where the highest power of the letter is 1.","글자의 최고 차수가 1인 식. 예 2x + 3","blood"),
("Quadratic expression","이차식","An expression where the highest power of the letter is 2.","글자의 최고 차수가 2인 식. 예 x² + 6x + 8","blood"),
("FOIL","FOIL(곱하는 순서)","First, Outer, Inner, Last — the order for multiplying two brackets.","앞×앞, 앞×뒤, 뒤×앞, 뒤×뒤 순서로 빠짐없이 곱하는 방법.","blood"),
("Like terms","동류항","Terms that have exactly the same letters and powers.","글자와 지수가 똑같은 항들. 6w 와 2w 는 동류항, w² 는 아니다.","blood"),
("Collect like terms","동류항을 모으다","To add or subtract terms that are alike.","같은 종류의 항끼리 더하거나 빼서 하나로 줄이는 것.","blood"),
("Difference of two squares","두 제곱의 차","(a + b)(a − b) = a² − b².","가운데 항이 서로 지워져 항이 두 개만 남는 꼴. (y+2)(y−2) = y² − 4","blood"),
("Perfect square","완전제곱식","(a ± b)² = a² ± 2ab + b².","(x+7)² 는 x²+49 가 아니다. 가운데 항 14x 가 반드시 나온다.","blood"),
("Sign","부호","Whether a number is positive or negative.","+ 인지 − 인지. 괄호 앞이 마이너스면 안의 부호가 전부 바뀐다.","blood"),
("Positive","양의","Greater than zero.","0보다 큰. 음수 × 음수 = 양수다.","blood"),
("Negative","음의","Less than zero.","0보다 작은. (−t)(−t) = +t² 가 된다.","blood"),
("Substitute back","다시 대입하다","To put your answer back into the expression to check it.","구한 답을 식에 도로 넣어 맞는지 확인하는 것.","blood"),
# ── gas : 대수 분수 · 공식 (2.5 · 2.6) ──
("Algebraic fraction","대수 분수","A fraction that has letters in the numerator or denominator.","분자나 분모에 글자가 든 분수. 예 x/3 + x/5","gas"),
("Numerator","분자","The number on the top of a fraction.","분수의 위쪽 수.","gas"),
("Denominator","분모","The number on the bottom of a fraction.","분수의 아래쪽 수.","gas"),
("Common denominator","공통분모","A denominator that both fractions can share.","두 분수가 함께 쓸 수 있는 분모. 보통 두 분모를 곱해서 만든다.","gas"),
("Lowest common denominator","최소공통분모","The smallest denominator both fractions can share.","공통분모 중 가장 작은 것. 10과 8이면 40 이다.","gas"),
("Lowest common multiple","최소공배수","The smallest number that is a multiple of both numbers.","두 수의 공배수 중 가장 작은 수. 줄여서 LCM 이라 쓴다.","gas"),
("Single fraction","하나의 분수","One fraction, after two have been combined.","두 분수를 합쳐 하나로 만든 것. 'Express as a single fraction' 지시문으로 나온다.","gas"),
("Simplified fraction","기약분수","A fraction reduced as far as it will go.","더 약분할 수 없을 때까지 줄인 분수.","gas"),
("Equation","방정식","Two expressions joined by an equals sign.","등호가 있는 식. 값을 구해 풀 수 있다.","gas"),
("Solve","풀다","To find the value of the unknown letter.","모르는 글자의 값을 찾아내는 것.","gas"),
("Quadratic equation","이차방정식","An equation with a squared term as its highest power.","x² 가 들어간 방정식. 인수분해하면 답이 보통 두 개 나온다.","gas"),
("Factorise","인수분해하다","To write an expression as a product of brackets.","괄호의 곱으로 바꾸는 것. x²−9x+18 = (x−3)(x−6)","gas"),
("Unknown","미지수","The letter whose value you are trying to find.","값을 모르는 글자. 보통 x 로 쓴다.","gas"),
("Derive a formula","공식을 세우다","To build a formula from the information in a question.","문제의 조건을 읽고 공식을 만들어 내는 것. 2.6 단원 제목이다.","gas"),
("Subject of a formula","공식의 주어","The letter on its own, usually on the left of the equals sign.","혼자 남아 있는 글자. P = W + RH 에서는 P 가 주어다.","gas"),
("Change the subject","주어를 바꾸다","To rearrange a formula so a different letter stands alone.","구하려는 글자만 남도록 공식을 정리하는 것. H = (P − W)/R","gas"),
("Rearrange","정리하다","To move terms around to a different arrangement.","항을 옮겨 식의 모양을 바꾸는 것.","gas"),
("Inverse operation","역연산","The operation that undoes another one.","반대 연산. 더하기↔빼기, 곱하기↔나누기.","gas"),
("Fixed amount","고정된 금액","An amount that stays the same whatever happens.","조건이 달라져도 변하지 않는 값. 하루 고정급 W 같은 것.","gas"),
("Per hour","시간당","For each hour.","한 시간마다. 시간당 R달러면 H시간에 RH달러다.","gas"),
]
CATS = [("organ","🔤 식의 기본 Expressions"),("process","🔟 지수 Indices"),
        ("blood","✖️ 괄호 전개 Expanding"),("gas","➗ 분수·공식 Fractions & formulae")]
